// Champions Meeting (CM) preset data for umalator-global's PRESET dropdown -- the Global
// dataset (see ../presets.ts for the JP counterpart, and ../docs/cm-presets.md for the schedule
// these dates feed into, the ground-condition label mapping below, and the lap-1-vs-lap-2
// course/condition sourcing story for ids 12-24).
//
// See ../presets.ts's header comment for why this is a hand-maintained `.ts` module (not JSON)
// validated with `satisfies`, and why its enum-ish fields are the engine-canonical member names
// from uma-skill-tools/RaceParameters.ts rather than any UI's display label. That distinction is
// exactly what this file used to get wrong: four entries below used to read `ground: 'Firm'`,
// mirroring the *Global UI's own label* for GroundCondition.Good (1) instead of the enum member
// name -- 'Firm' doesn't exist as a GroundCondition member at all (the real scale is
// Good=1/Yielding=2/Soft=3/Heavy=4, which Global's GroundSelect relabels Firm/Good/Soft/Heavy).
// Under the old literal `GroundCondition.Firm` silently evaluated to `undefined` and was rescued
// by RaceParams' record default of `Good`, which happened to *display* as "Firm" again -- correct
// output purely by luck (see docs/cm-presets.md for the full account). Written out here as
// `'Good'` fixes that for real, with `satisfies` now able to catch a recurrence at compile time.
import type { RawPreset } from '../umalator/racePresets';

export default [
	// ids 20-24: dates are estimated (upstream's own list doesn't reach these yet) -
	// course/conditions come from JP's original 2022-2023 debut run of each cup (Global's 2nd
	// zodiac lap replays JP's historical back-catalog, not JP's current rotation). id 19 Scorpio
	// Cup 2's date was also originally marked estimated but has since been confirmed correct, so
	// it no longer carries the flag.
	{
		id: 24,
		type: 'CM',
		name: 'Aries Cup 2',
		date: '2026-12-29',
		estimated: true,
		courseId: 10811,
		season: 'Spring',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 23,
		type: 'CM',
		name: 'Pisces Cup 2',
		date: '2026-12-08',
		estimated: true,
		courseId: 10504,
		season: 'Spring',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 22,
		type: 'CM',
		name: 'Aquarius Cup 2',
		date: '2026-11-17',
		estimated: true,
		courseId: 10611,
		season: 'Winter',
		ground: 'Soft',
		weather: 'Snowy',
		time: 'Midday',
	},
	{
		id: 21,
		type: 'CM',
		name: 'Capricorn Cup 2',
		date: '2026-10-27',
		estimated: true,
		courseId: 10701,
		season: 'Winter',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 20,
		type: 'CM',
		name: 'Sagittarius Cup 2',
		date: '2026-10-06',
		estimated: true,
		courseId: 10506,
		season: 'Winter',
		ground: 'Good',
		weather: 'Cloudy',
		time: 'Midday',
	},
	{
		id: 19,
		type: 'CM',
		name: 'Scorpio Cup 2',
		date: '2026-09-15',
		courseId: 10808,
		season: 'Autumn',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 18,
		type: 'CM',
		name: 'Libra Cup 2',
		date: '2026-08-25',
		courseId: 10903,
		season: 'Autumn',
		ground: 'Good',
		weather: 'Cloudy',
		time: 'Midday',
	},
	{
		id: 17,
		type: 'CM',
		name: 'Virgo Cup 2',
		date: '2026-08-05',
		courseId: 11103,
		season: 'Autumn',
		ground: 'Yielding',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 16,
		type: 'CM',
		name: 'Leo Cup 2',
		date: '2026-07-25',
		courseId: 10501,
		season: 'Summer',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 15,
		type: 'CM',
		name: 'Cancer Cup 2',
		date: '2026-06-24',
		courseId: 10906,
		season: 'Summer',
		ground: 'Yielding',
		weather: 'Cloudy',
		time: 'Midday',
	},
	{
		id: 14,
		type: 'CM',
		name: 'Gemini Cup 2',
		date: '2026-06-04',
		courseId: 10602,
		season: 'Spring',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 13,
		type: 'CM',
		name: 'Taurus Cup 2',
		date: '2026-05-10',
		courseId: 10606,
		season: 'Spring',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 12,
		type: 'CM',
		name: 'Aries Cup',
		date: '2026-04-23',
		courseId: 10504,
		season: 'Spring',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 11,
		type: 'CM',
		name: 'Pisces Cup',
		date: '2026-03',
		courseId: 10914,
		season: 'Spring',
		ground: 'Heavy',
		weather: 'Rainy',
		time: 'Midday',
	},
	{
		id: 10,
		type: 'CM',
		name: 'Aquarius Cup',
		date: '2026-02',
		courseId: 10611,
		season: 'Winter',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 9,
		type: 'CM',
		name: 'Capricorn Cup',
		date: '2026-02',
		courseId: 10701,
		season: 'Winter',
		ground: 'Soft',
		weather: 'Snowy',
		time: 'Midday',
	},
	{
		id: 8,
		type: 'CM',
		name: 'Sagittarius Cup',
		date: '2026-01',
		courseId: 10506,
		season: 'Winter',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 7,
		type: 'CM',
		name: 'Scorpio Cup',
		date: '2026-01',
		courseId: 10604,
		season: 'Autumn',
		ground: 'Soft',
		weather: 'Rainy',
		time: 'Midday',
	},
	{
		id: 6,
		type: 'CM',
		name: 'Libra Cup',
		date: '2025-12',
		courseId: 10810,
		season: 'Autumn',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 5,
		type: 'CM',
		name: 'Virgo Cup',
		date: '2025-11-20',
		courseId: 10903,
		season: 'Autumn',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 4,
		type: 'CM',
		name: 'Leo Cup',
		date: '2025-10-30',
		courseId: 10906,
		season: 'Summer',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 3,
		type: 'CM',
		name: 'Cancer Cup',
		date: '2025-10-07',
		courseId: 10602,
		season: 'Summer',
		ground: 'Yielding',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 2,
		type: 'CM',
		name: 'Gemini Cup',
		date: '2025-09',
		courseId: 10811,
		season: 'Spring',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
	{
		id: 1,
		type: 'CM',
		name: 'Taurus Cup',
		date: '2025-08',
		courseId: 10606,
		season: 'Spring',
		ground: 'Good',
		weather: 'Sunny',
		time: 'Midday',
	},
] satisfies readonly RawPreset[];
